Repository kiesraad/abacus, pull requests merged in 2025-09, with the labels that each got.

#2060 Link report page to committee session and prevent resuming previous session
  backend/openapi.json
  backend/src/committee_session/api.rs
  backend/src/election/api.rs
  backend/tests/committee_session_integration_test.rs
  backend/tests/election_integration_test.rs
  backend/tests/shared/mod.rs
  frontend/.storybook/preview.tsx
  frontend/e2e-tests/fixtures.ts
  frontend/src/components/navbar/NavBarLinks.tsx
  frontend/src/features/apportionment/components/ApportionmentPage.tsx
  frontend/src/features/data_entry/components/AbortDataEntryControl.test.tsx
  frontend/src/features/data_entry_home/components/DataEntryHomePage.tsx
  frontend/src/features/election_management/components/CommitteeSessionCard.test.tsx
  frontend/src/features/election_management/components/CommitteeSessionCard.tsx
  frontend/src/features/election_management/components/ElectionHomePage.test.tsx
  frontend/src/features/election_management/components/ElectionHomePage.tsx
  frontend/src/features/election_management/components/report/ElectionReportPage.test.tsx
  frontend/src/features/election_management/components/report/ElectionReportPage.tsx
  frontend/src/features/election_management/components/report/FinishDataEntryPage.test.tsx
  frontend/src/features/election_management/components/report/FinishDataEntryPage.tsx
  frontend/src/features/election_management/components/update/CommitteeSessionDetailsPage.test.tsx
  frontend/src/features/election_management/components/update/CommitteeSessionDetailsPage.tsx
  frontend/src/features/election_management/components/update/NumberOfVotersPage.tsx
  frontend/src/features/election_management/routes.tsx
  frontend/src/features/election_status/components/ElectionStatusPage.tsx
  frontend/src/features/investigations/components/InvestigationsOverview.tsx
  frontend/src/hooks/election/ElectionProvider.tsx
  frontend/src/hooks/election/ElectionProviderContext.tsx
  frontend/src/hooks/election/useElection.ts
  frontend/src/hooks/election/useElectionDataRequest.ts
  frontend/src/testing/api-mocks/CommitteeSessionMockData.ts
  frontend/src/testing/api-mocks/ElectionMockData.ts
  frontend/src/testing/api-mocks/RequestHandlers.ts
  frontend/src/types/generated/openapi.ts
Labels: backend, frontend

#2090 FileInput storybook tests
  frontend/src/components/ui/FileInput/FileInput.stories.tsx
  frontend/src/components/ui/FileInput/FileInput.test.tsx
Labels: tests

#2072 Update report Na 31-2 with new model fields
  backend/.sqlx/query-038f37132d44a6b46da140add76eade35a0f40af3c1130182da5abe78dd9db20.json
  backend/.sqlx/query-5bc73cd3b5d8ac6b386b893017f190978c17106a62203037b0e3e5c4fbdb2769.json
  backend/.sqlx/query-67c520af5da6674c980fc4e47cc905c4706647beba3032671d594f35c57ceaab.json
  backend/.sqlx/query-6b9728a05eeddc52ec2211636b51f5eea7d8ca0db8b2d6e17c5177142699aff5.json
  backend/.sqlx/query-91eb8f31ec9831cd17292e9082b508703c63178afae1182dc3b0205d6fa0aae3.json
  backend/.sqlx/query-994b41b02bf6d050e86109cb5bb1c08425ccbb94036e7efbcf2d17770ba1c0db.json
  backend/.sqlx/query-c446bcbcfc4ea3f2d57b66873f6d86b65e3ba23086b7c37f1959aec23993a939.json
  backend/fixtures/election_2.sql
  backend/openapi.json
  backend/src/apportionment/mod.rs
  backend/src/audit_log/audit_event.rs
  backend/src/committee_session/api.rs
  backend/src/pdf_gen/mod.rs
  backend/src/pdf_gen/models/model_n_10_2.rs
  backend/src/pdf_gen/models/model_na_31_2.rs
  backend/src/polling_station/repository.rs
  backend/src/polling_station/structs.rs
  backend/src/summary/mod.rs
  backend/templates/common/scripts.typ
  backend/templates/inputs/model-n-10-2.json
  backend/templates/inputs/model-na-31-2-bijlage1.json
  backend/templates/inputs/model-na-31-2.json
  backend/templates/model-na-31-1.typ
  backend/templates/model-na-31-2.typ
  frontend/src/features/apportionment/testing/gte-19-seats-and-p9.ts
  frontend/src/features/apportionment/testing/gte-19-seats.ts
  frontend/src/features/apportionment/testing/lt-19-seats-and-p10.ts
  frontend/src/features/apportionment/testing/lt-19-seats-and-p9-and-p10.ts
  frontend/src/features/apportionment/testing/lt-19-seats.ts
  frontend/src/types/generated/openapi.ts
Labels: typst

#2101 Fixed keyboard hint styling regression
  frontend/src/components/ui/KeyboardKeys/KeyboardKeys.module.css
Labels: bug

#2091 Fix signout does not work during election creation bug
  frontend/src/features/election_create/components/AbortModal.tsx
  frontend/src/features/election_create/components/ElectionCreate.test.tsx
  frontend/src/features/election_create/components/ElectionCreateContextProvider.tsx
Labels: bug

#2108 Remove unused `SummaryDifferenceCountsCompare` struct
  backend/src/summary/mod.rs
Labels: backend

#2098 Prepare input grid for adding corrigendum column
  frontend/src/components/data_entry/subsections/InputGridSubsection.tsx
  frontend/src/components/ui/InputGrid/InputGrid.module.css
  frontend/src/components/ui/InputGrid/InputGrid.stories.tsx
  frontend/src/components/ui/InputGrid/InputGrid.tsx
  frontend/src/components/ui/InputGrid/InputGridRow.test.tsx
  frontend/src/components/ui/InputGrid/InputGridRow.tsx
  frontend/src/features/data_entry/components/DataEntrySection.module.css
  frontend/src/features/data_entry/components/DataEntrySection.tsx
  frontend/src/features/data_entry/testing/test.utils.ts
Labels: frontend

#2117 use cases: create new session before preparing session
  documentatie/use-cases/gsb-tweede-zitting.md
Labels: documentation

#2118 Bugfix: numbers were not formatted when coming back to data entry section
  frontend/src/components/ui/InputGrid/InputGrid.stories.tsx
  frontend/src/components/ui/InputGrid/InputGridRow.tsx
  frontend/src/components/ui/NumberInput/NumberInput.test.tsx
  frontend/src/components/ui/NumberInput/NumberInput.tsx
Labels: bug

#2132 Implemented design of ReportPage
  frontend/e2e-tests/page-objects/election/ElectionReportPgObj.ts
  frontend/e2e-tests/tests/full-flow.e2e.ts
  frontend/e2e-tests/tests/pdf-rendering.e2e.ts
  frontend/src/assets/icons/checkVerified.svg
  frontend/src/assets/icons/download.svg
  frontend/src/assets/icons/file.svg
  frontend/src/assets/icons/filter.svg
  frontend/src/components/generated/icons.tsx
  frontend/src/components/ui/DownloadButton/DownloadButton.module.css
  frontend/src/features/election_management/components/ElectionManagement.module.css
  frontend/src/features/election_management/components/report/ElectionReportPage.test.tsx
  frontend/src/features/election_management/components/report/ElectionReportPage.tsx
  frontend/src/i18n/locales/nl/election_management.json
  frontend/src/styles/typography.css
  frontend/src/styles/variables.css
Labels: frontend, ux debt

#2155 update and dedupe frontend dependencies
  frontend/package-lock.json
Labels: frontend

#2185 Add definitions to validation rules
  documentatie/use-cases/validatieregels-plausibiliteitschecks-tellingen.md
Labels: documentation

#2201 Update software architecture diagrams
  documentatie/softwarearchitectuur/diagrammen/component-backend.png
  documentatie/softwarearchitectuur/diagrammen/container.png
  documentatie/softwarearchitectuur/diagrammen/systeemlandschap.png
Labels: documentation
